---
Name: userdocs-config
---
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.userdocsmanifest:
    factory: 'SilverStripe\Core\Cache\CacheFactory'
    constructor:
      namespace: 'userdocsmanifest'
  # Commonmark markdown converter injection config
  League\CommonMark\Environment\Environment.userdocs:
    factory: 'SilverStripe\UserDocs\Admin\MarkdownEnvironmentFactory'
    constructor:
      config:
        alert:
          icons:
            active: true
        heading_permalink:
          insert: 'after'
          symbol: '#'
        table_of_contents:
          min_heading_level: 2
      extensions:
        CommonMarkCoreExtension: '%$League\CommonMark\Extension\CommonMark\CommonMarkCoreExtension'
        FrontMatterExtension: '%$League\CommonMark\Extension\FrontMatter\FrontMatterExtension'
        GithubFlavoredMarkdownExtension: '%$League\CommonMark\Extension\GithubFlavoredMarkdownExtension'
        HeadingPermalinkExtension: '%$League\CommonMark\Extension\HeadingPermalink\HeadingPermalinkExtension'
        TableOfContentsExtension: '%$League\CommonMark\Extension\TableOfContents\TableOfContentsExtension'
        AlertExtension: '%$PomoDocs\CommonMark\Alert\AlertExtension'
  League\CommonMark\MarkdownConverter.userdocs:
    class: 'League\CommonMark\MarkdownConverter'
    constructor:
      environment: '%$League\CommonMark\Environment\Environment.userdocs'
